---
name: final-project
break: true
indent: 4
---
README.md:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "{Your Name Here}" --count -0 --exact
    
project:
    reflection.md:
        ConfirmFileExists
        MatchFileFragment --fragment "TODO" --count 0 --exact
        CountFileWords --count 750
            
writing:
    reflection.md:
        ConfirmFileExists
        CountMarkdownTags --tag "heading" --count 5
        CountMarkdownTags --tag "code_block" --count 1
            
CountCommits --count 5
ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle run"